config/routes.rb
Rails.application.routes.draw do

  root 'tracks#index'
  get 'tracks/:id' => 'tracks#show', as: :track
  get '/tags' => 'tag#index'
  get '/tags/:id' => 'tag#show', as: :tag

  resource :tracks

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  belongs_to :track

end

app/models/track.rb
class Track < ActiveRecord::Base

  has_many :tags

end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
  def show
    @albums = Album.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tag_controller.rb
class TagController < ApplicationController

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(track_params)
    if @tag.save
      redirect_to root_path
    else
      render root_path
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @tracks = Track.find_by_tag(@tag)
  end


    private

    def tag_params
      params.require(:tag).permit(:name,:track_id)
    end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController


  def index
    @all_tracks = Track.all
    @new_track = Track.new
  end
    
  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to root_path
    else
      render root_path
    end
  end

  def show
    @track = Track.find(params[:id])
    @tags = @track.tags
  end


  private

  def track_params
    params.require(:track).permit(:name,:artist,:album,:year_written)
  end


end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tag/index.html.erb
<h3>These are the current tags:</h3>

<% @tags.each do |t| %>
    <p><%= t.name %></p>
<% end %>

app/views/tag/show.html.erb
    <p><strong><%= @tag.name %></strong></p>

app/views/tracks/index.html.erb
<h1>Enter new track:</h1>

<div class = "enter-track">
    <%= form_for (@new_track) do |t| %>
       <div class = "new-name">
            <div class = "title">
                <%= t.text_field :name, placeholder: "Name" %>
            </div>
            <div class = "artist">
                <%= t.text_field :artist, placeholder: "Artist" %>
            </div>
            <div class = "album">
                <strong><%= t.text_field :album, placeholder: "Album" %></strong>
            </div>  
            <div class = "year-written">
                <%= t.text_field :year_written, placeholder: "Year" %>
            </div>  

             <div class = "space">
                <%= t.submit "Enter Track"%>
            </div>  

<!--             <%= check_box_tag(:classical) %>
            <%= label_tag(:classical, "Classical") %>
            <%= check_box_tag(:rock) %>
            <%= label_tag(:rock, "Rock") %>
            <%= check_box_tag(:electronica) %>
            <%= label_tag(:electronica, "Electronica") %> -->


        </div>      
    <% end %>
</div>

<div class = "display-tracks">

    <% @all_tracks.each do |t| %>
        <p class = "main-info"><strong><%= link_to t.name, track_path(t) %> </strong> by <em><%= t.artist %></em></p>
        <p class = "supporting-info"><%= t.album %>, <%=  t.year_written %></p>
    <% end %>
</div>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<h3><em><%= @track.album %></em>, <%= @track.year_written %></h3>
<h3>By: <%= @track.artist %> </h3>

<h2>Tags:</h2>
<br>
<% @tags.each do |t| %>
<%= t.name %>
<% end %>